default: &default
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  jwt_expiration_hours: 3
  jwt_refresh_expiration_hours: 720

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
